spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ma-osawa-database
    username: ********
    password: ********

cloud:
  aws:
    stack:
      auto: false
