rds:
  identifier: ${RDS_IDENTIFIER:ma-osawa-rds}
  password: ${RDS_PASSWORD:********}

cloud:
  aws:
    credentials:
      profile-name:
      instance-profile: false
    region:
      auto: false
      static: ap-northeast-1
    stack:
      auto: false
